employee_management1/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :employees
  get 'posts/create'
  resources :employees
  resources :posts
  resources :events
  get 'dashboard/hrdashboard'
   
end

employee_management1/app/models/event.rb
class Event < ApplicationRecord
	belongs_to :employee
	has_many :likes, dependent: :destroy
    has_many :likes, as: :likeable	
end

employee_management1/app/controllers/events_controller.rb
class EventsController < ApplicationController 
  # before_action :check_role

  def new
    @event=Event.new
 
  end

  def create
    @event=Event.new(event_params)
    if @event.save
      #render json:@event
      redirect_to employees_path,notice: 'event created successfully'
    else
      render :new
    end 
  end 


  def update
  end

  def delete
  end

  def show
  end

  def all
  end

  def check_role
    
  end 

  private
  def event_params
    params.require(:event).permit(:employee_id,:name,:location)
  end 
end


 

employee_management1/app/helpers/event_helper.rb
module EventHelper
end

employee_management1/app/views/events/all.html.erb
<h1>Event#all</h1>
<p>Find me in app/views/event/all.html.erb</p>

employee_management1/app/views/events/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>

employee_management1/app/views/events/delete.html.erb
<h1>Event#delete</h1>
<p>Find me in app/views/event/delete.html.erb</p>

employee_management1/app/views/events/index.html.erb
<h1>this</h1>

employee_management1/app/views/events/new.html.erb
<div class="container d-flex">
  <%= form_for @event do |f| %>

   <%= f.label :name, class: 'form-label' %>
   <%= f.text_field :name, class: 'form-control' %><br/>

   <%= f.submit class: "btn btn-primary" %>

  <% end %>

</div>

employee_management1/app/views/events/show.html.erb
<div class="container d-flex">
  <div class="row">
  <div class="col">
  <h1 class="m-1"> <%= @event.name %> </h1>
  <%= link_to "create a new events",new_event_path,class: "btn btn-primary" %>
</div>
</div>
</div>

employee_management1/app/views/events/update.html.erb
<h1>Event#update</h1>
<p>Find me in app/views/event/update.html.erb</p>